"use client";

import { useState } from "react";

type SectionAssessment = {
  section: string;
  subject: string;
  summary: string;
};

type SummaryData = {
  overall_risk: "LOW" | "MEDIUM" | "HIGH";
  risk_score: number;
  sections: SectionAssessment[];
  remarks: string;
};

export type RiskSummaryProps = {
  data: SummaryData;
  meta: {
    provider: string;
    model: string;
    generated_by: string;
  };
};

export default function RiskSummary({ data, meta }: RiskSummaryProps) {
  const [expandedRow, setExpandedRow] = useState<number | null>(null);
  return (
    <div className="flex flex-col h-full overflow-auto gap-2">
      {/* 🔹 Summary */}
      <div className="p-4 border rounded-lg shadow-sm bg-white">
        <h2 className="text-xl font-semibold mb-2">Summary</h2>
        <p className="text-gray-700">{data.remarks}</p>
      </div>

      {/* 🔹 Risk Overview */}
      <div className="flex gap-6">
        <div className="p-4 border rounded-lg w-1/2 text-center">
          <p className="text-sm text-gray-500">Overall Risk</p>
          <p className="text-2xl font-bold">{data.overall_risk}</p>
        </div>

        <div className="p-4 border rounded-lg w-1/2 text-center">
          <p className="text-sm text-gray-500">Risk Score</p>
          <p className="text-2xl font-bold">{data.risk_score}</p>
        </div>
      </div>

      <div className="flex gap-6 w-full">
        <table className="min-w-full table-fixed border border-gray-200 rounded-lg overflow-hidden">
          <thead className="bg-gray-100">
            <tr>
              <th className="px-4 py-3 text-left text-sm font-semibold text-gray-700 border-b w-5">
                S No.
              </th>
              <th className="px-4 py-3 text-left text-sm font-semibold text-gray-700 border-b w-25">
                Section
              </th>
              <th className="px-4 py-3 text-left text-sm font-semibold text-gray-700 border-b w-25">
                Subject
              </th>
              <th className="px-4 py-3 text-left text-sm font-semibold text-gray-700 border-b">
                {/* no width — takes all remaining space */}
                Summary
              </th>
            </tr>
          </thead>

          <tbody className="divide-y divide-gray-200">
            {data.sections.map((sec, idx) => (
              <tr key={idx} className="hover:bg-gray-50 transition-colors">
                <td className="px-4 py-3 text-sm text-gray-600 w-5">
                  {idx + 1}
                </td>
                <td className="px-4 py-3 text-sm font-medium text-gray-800 w-25 wrap-break-word">
                  {sec.section}
                </td>
                <td className="px-4 py-3 text-sm text-gray-700 w-25 wrap-break-word">
                  {sec.subject}
                </td>
                <td className="px-4 py-3 text-sm text-gray-600">
                  <p className={expandedRow === idx ? "" : "line-clamp-3"}>
                    {sec.summary}
                  </p>
                  {sec.summary.length > 150 && (
                    <button
                      onClick={() =>
                        setExpandedRow(expandedRow === idx ? null : idx)
                      }
                      className="text-blue-500 text-xs mt-1"
                    >
                      {expandedRow === idx ? "Show less" : "Read more"}
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* 🔹 Meta */}
      <div className="text-sm text-gray-400 text-right">
        Generated by {meta.provider} ({meta.model})
        {meta.generated_by && ` : developed by - ${meta.generated_by}`}
      </div>
    </div>
  );
}
